name: marine_environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - anndata
  - bedtools
  - matplotlib
  - numpy
  - pandas
  - polars
  - psutil
  - pybedtools
  - pysam
  - scanpy
  - samtools
  - scipy
  - tqdm
