name: marine_environment_3_10
channels:
  - anaconda
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - matplotlib
  - pybedtools
  - _libgcc_mutex         
  - _openmp_mutex         
  - abseil-cpp            
  - arrow-cpp             
  - asttokens             
  - aws-c-common          
  - aws-c-event-stream    
  - aws-checksums         
  - aws-sdk-cpp           
  - backcall              
  - backports             
  - backports.zoneinfo    
  - blas                  
  - boost-cpp             
  - bottleneck            
  - brotli-python         
  - bzip2                 
  - c-ares                
  - ca-certificates       
  - certifi               
  - cffi                  
  - charset-normalizer    
  - colorama              
  - comm                  
  - cryptography          
  - debugpy               
  - decorator             
  - executing             
  - gflags                
  - glog                  
  - grpc-cpp              
  - icu                   
  - idna                  
  - importlib-metadata    
  - importlib_metadata    
  - intel-openmp          
  - ipykernel             
  - ipython               
  - jedi                  
  - jupyter_client        
  - jupyter_core          
  - krb5                  
  - ld_impl_linux-64      
  - libbrotlicommon       
  - libbrotlidec          
  - libbrotlienc          
  - libcurl               
  - libdeflate            
  - libedit               
  - libev                 
  - libevent              
  - libffi                
  - libgcc-ng             
  - libgfortran-ng        
  - libgfortran5          
  - libgomp               
  - libnghttp2            
  - libnsl                
  - libprotobuf           
  - libsodium             
  - libsqlite             
  - libssh2               
  - libstdcxx-ng          
  - libthrift             
  - libuuid               
  - libzlib               
  - lz4-c                 
  - matplotlib-inline     
  - mkl                   
  - mkl-service           
  - mkl_fft               
  - mkl_random            
  - ncurses               
  - nest-asyncio          
  - numexpr               
  - numpy                 
  - numpy-base            
  - openssl               
  - orc                   
  - packaging             
  - pandas                
  - parso                 
  - pexpect               
  - pickleshare           
  - pip                   
  - platformdirs          
  - polars                
  - pooch                 
  - prompt-toolkit        
  - psutil                
  - ptyprocess            
  - pure_eval             
  - pyarrow               
  - pycparser             
  - pygments              
  - pyopenssl             
  - pysam                 
  - pysocks               
  - python                
  - python-dateutil       
  - python-tzdata         
  - python_abi            
  - pytz                  
  - pyzmq                 
  - re2                   
  - readline              
  - requests  
  - scalene
  - scipy                 
  - setuptools            
  - six                   
  - snappy                
  - stack_data            
  - tbb                   
  - tk                    
  - tornado               
  - tqdm                  
  - traitlets             
  - typing_extensions     
  - tzdata                
  - urllib3               
  - utf8proc              
  - wcwidth               
  - wheel                 
  - xz                    
  - zeromq                
  - zipp                  
  - zlib                  
  - zstd                  