name: integration_test_cli

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Install Mamba
        run: |
          conda install -c conda-forge mamba -y
          
      - name: Print environment variables
        run: |
          printenv
          ls /usr/share/miniconda/bin/

      - name: Create Conda Environment
        run: |
          /usr/share/miniconda/bin/mamba create -n marine_environment python=3.10 -y

      - name: Source bashrc and activate environment
        run: |
          source /home/runner/.bashrc

      - name: Initialize mamba and activate
        run: |    
          /usr/share/miniconda/bin/mamba init
          /usr/share/miniconda/bin/mamba activate marine_environment

      - name: Execute Integration Tests
        run: |
          source /home/runner/.bashrc
          /usr/share/miniconda/bin/mamba init
          /usr/share/miniconda/bin/mamba activate marine_environment
          bash tests/integration_tests_run.sh
