name: integration_test_cli

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Install Mamba
        run: |
          conda install -c conda-forge mamba -y
          
      - name: Print environment variables
        run: |
          printenv
          ls /usr/share/miniconda/bin/
          
      - name: Create Conda Environment
        run: |
          /usr/share/miniconda/bin/mamba create -n marine_environment python=3.10 -y
          conda activate marine_environment
          /usr/share/miniconda/bin/mamba env update -n marine_environment -f marine_environment.yml

      - name: Execute Integration Tests
        run: |
          conda activate marine_environment
          bash tests/integration_tests_run.sh
