name: integration_test_macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Mambaforge (macOS Arm64)
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge   # installs Mamba-enabled Miniforge
          architecture: arm64             # force the arm64 installer
          python-version: 3.10            # (optional) pin base Python
          activate-environment: false
          auto-update-conda: true

      - name: Create Conda Environment (macOS)
        run: |
          # `mamba` is now on PATH
          mamba create -n marine_environment python=3.10 -y
          mamba env update -n marine_environment --file marine_environment2.yaml

      - name: Run Integration Tests (macOS)
        run: |
          conda init bash
          CONDA_BASE=$(conda info --base) ; source $CONDA_BASE/etc/profile.d/conda.sh
          conda activate marine_environment
          cd tests
          bash integration_tests_run.sh $(which python)
