name: integration_test_cli

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Install Mamba
        run: |
          conda install -c conda-forge mamba=1.5.12 -y 
          
      - name: Print conda folder contents
        run: |
      
          ls /usr/share/miniconda/bin/
          ls /usr/share/miniconda/
           
      - name: Create Conda Environment
        run: |
          /usr/share/miniconda/bin/mamba create -n marine_environment python=3.10 -y
          /usr/share/miniconda/bin/mamba env update -n marine_environment --file marine_environment2.yaml

      - name: Print marine_environment bin folder contents
        run: |
          ls /usr/share/miniconda/envs/marine_environment/bin

                              
      - name: Execute Integration Tests
        run: |
          echo "running source"
          source /home/runner/.bashrc
          echo "running init"
          conda init bash

          CONDA_BASE=$(conda info --base) ; source $CONDA_BASE/etc/profile.d/conda.sh
          
          echo "running activate"
          conda activate marine_environment

          which python

          echo "creating marine base dir environment variable..."
          export MARINE=$(pwd)
          echo $MARINE
          ls $MARINE

          echo "Adding marine to path..."
          export PATH=$PATH:$(pwd)
          echo $PATH
          
          echo "running test"
          cd tests
          pwd

          bash integration_tests_run.sh /usr/share/miniconda/envs/marine_environment/bin/python
