name: integration_test_cli

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Install Mamba
        run: |
          conda install -c conda-forge mamba -y
          
      - name: Print conda folder contents
        run: |
      
          ls /usr/share/miniconda/bin/

      - name: Create Conda Environment
        run: |
          /usr/share/miniconda/bin/mamba create -n marine_environment python=3.10 -y

      - name: Init mamba environment
        run: |    
          /usr/share/miniconda/bin/mamba init
          
      - name: Execute Integration Tests
        run: |
          echo "running source"
          source /home/runner/.bashrc
          echo "running init"
          /usr/share/miniconda/bin/mamba init
          echo "running activate"
          /usr/share/miniconda/bin/conda activate marine_environment
          echo "running test"
          bash tests/integration_tests_run.sh
