name: integration_test_cli

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Install Mamba
        run: |
          conda install -c conda-forge mamba -y

      - name: Find Mamba executable path
        run: |
          MAMBA_PATH=$(which mamba)
          echo "Mamba is installed at: $MAMBA_PATH"

      - name: Create Conda Environment
        run: |
          $MAMBA_PATH create -n marine_environment python=3.10 -y
          conda activate marine_environment
          $MAMBA_PATH env update -n marine_environment -f marine_environment.yml

      - name: Execute Integration Tests
        run: |
          conda activate marine_environment
          bash tests/integration_tests_run.sh
